# Generated by Django 6.0.2 on 2026-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={"verbose_name": "Попытка", "verbose_name_plural": "Попытки"},
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(verbose_name="Окончание"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(verbose_name="Начало"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(verbose_name="Ответ сервера"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Тема"),
        ),
    ]
